apiVersion: apps/v1
kind: Deployment
metadata:
  name: complaint-analyzer
  namespace: "2410710"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: complaint-analyzer
  template:
    metadata:
      labels:
        app: complaint-analyzer
    spec:
      containers:
        - name: complaint-analyzer
          image: complaint-analyzer:latest   # image NOT used in CI
          ports:
            - containerPort: 8000
