apiVersion: v1
kind: Service
metadata:
  name: complaint-analyzer-service
spec:
  selector:
    app: complaint-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
